// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGng9weVvNaC19GBCH1uDYfxD5Ys61TVU',
    appId: '1:1046627275582:web:0358eef4b7e759ec17126f',
    messagingSenderId: '1046627275582',
    projectId: 'my-workspace-cc686',
    authDomain: 'my-workspace-cc686.firebaseapp.com',
    storageBucket: 'my-workspace-cc686.firebasestorage.app',
    measurementId: 'G-N2J2ZVBDHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_j5EJDvwzhstIc4bwb2D8Zsj_xr47dY0',
    appId: '1:1046627275582:android:2c362a5894d6b46717126f',
    messagingSenderId: '1046627275582',
    projectId: 'my-workspace-cc686',
    storageBucket: 'my-workspace-cc686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqp_fVmjBzCGQXumnBtosP44tNsoNqlY',
    appId: '1:1046627275582:ios:9c8620771b7555dd17126f',
    messagingSenderId: '1046627275582',
    projectId: 'my-workspace-cc686',
    storageBucket: 'my-workspace-cc686.firebasestorage.app',
    androidClientId: '1046627275582-4mc29n5t5du3phk0ckiv7nvtq8s6i54d.apps.googleusercontent.com',
    iosClientId: '1046627275582-p9cb8i7ii644st6b4nhrp0ei56it2igm.apps.googleusercontent.com',
    iosBundleId: 'com.duynguyen.myworkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqp_fVmjBzCGQXumnBtosP44tNsoNqlY',
    appId: '1:1046627275582:ios:e458267d0b87bd7317126f',
    messagingSenderId: '1046627275582',
    projectId: 'my-workspace-cc686',
    storageBucket: 'my-workspace-cc686.firebasestorage.app',
    iosClientId: '1046627275582-eo690khipq7bhi5mourguf6poomiur0r.apps.googleusercontent.com',
    iosBundleId: 'com.duynguyen.myworkspace.myWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGng9weVvNaC19GBCH1uDYfxD5Ys61TVU',
    appId: '1:1046627275582:web:d51b02bd859189b517126f',
    messagingSenderId: '1046627275582',
    projectId: 'my-workspace-cc686',
    authDomain: 'my-workspace-cc686.firebaseapp.com',
    storageBucket: 'my-workspace-cc686.firebasestorage.app',
    measurementId: 'G-DS9J6Y6X7K',
  );
}