# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build app"
  lane :build_and_upload_to_testflight do
    keychain_name = "github_ci_keychain"
    keychain_password = "github_ci_password"
    release_notes = ENV["RELEASE_NOTES"] || "Automated build from Github Actions."

    puts "Release notes:\n#{release_notes}"

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

    build_number = latest_testflight_build_number + 1
    puts "Build number: #{build_number}"

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: build_number
    )

    sh("flutter build ipa --release --dart-define-from-file=.env --build-number=#{build_number} --no-codesign --no-pub")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: ENV["APPLE_TEAM_ID"]
    )

    upload_to_testflight(
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      skip_waiting_for_build_processing: true,
      changelog: release_notes
    )
  end

  desc "Sync ios development signing (certificates & profiles)"
  lane :signing do
    match(
      type: "development",
      readonly: true
    )
  end

  desc "Generate ios app store signing credentials (certificates & profiles)"
  lane :generate_signing do |options|
    type = options[:type]

    if type == nil
      UI.user_error!("You must provide a profile type (appstore | development | adhoc)")
    end

    match(
      type: type,
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      force_for_new_devices: true
    )
  end

  desc "Remove ios signing credentials (certificates & profiles)"
  lane :remove_signing do
    match_nuke(
      type: "appstore",
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )
  end

end
