# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build app"
  lane :build do
    xcodes(version: ENV["XCODE_VERSION"])

    signing

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )

    publish
  end

  desc "Publish app"
  lane :publish do
    upload_to_testflight(
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      skip_waiting_for_build_processing: true
    )
  end

  desc "Sync ios signing (certificates & profiles)"
  lane :signing do
    match(
      type: "appstore",
      readonly: true
    )
  end

  desc "Generate ios signing credentials (certificates & profiles)"
  lane :generate_signing do
    match(
      type: "appstore",
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )
  end

  desc "Remove ios signing credentials (certificates & profiles)"
  lane :remove_signing do
    match_nuke(
      type: "appstore",
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )
  end

end
