# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build app"
  lane :build do
    keychain_name = "github_ci_keychain"
    keychain_password = "github_ci_password"
    release_notes = ENV["RELEASE_NOTES"] || "Automated build from Github Actions."

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )

    upload_to_testflight(
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      skip_waiting_for_build_processing: true,
      changelog: release_notes
    )
  end

  desc "Sync ios signing (certificates & profiles)"
  lane :signing do
    match(
      type: "appstore",
      readonly: true
    )
  end

  desc "Generate ios signing credentials (certificates & profiles)"
  lane :generate_signing do
    match(
      type: "appstore",
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )
  end

  desc "Remove ios signing credentials (certificates & profiles)"
  lane :remove_signing do
    match_nuke(
      type: "appstore",
      api_key_path: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )
  end

end
