# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build & Upload APK to Firebase App Distribution"
  lane :build_and_upload_to_firebase_app_distribution do
    release_notes = ENV["RELEASE_NOTES"] || "Automated build from Github Actions."

    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_ANDROID_APP_ID"]
    )

    newVersionCode = 1
    if latest_release
      newVersionCode = latest_release[:buildVersion].to_i + 1
    end
    
    build_android_app(
      task: "assemble",
      build_type: "Release",
      properties: {
        "versionCode" => newVersionCode
      }
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      release_notes: release_notes,
      groups: "internal"
    )
  end
end
