# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build & Upload APK to Firebase App Distribution"
  lane :build_and_upload_to_firebase_app_distribution do
    release_notes = ENV["RELEASE_NOTES"] || "Automated build from Github Actions."

    puts "Release notes:\n#{release_notes}"

    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_ANDROID_APP_ID"]
    )

    build_number = 1
    if latest_release
      build_number = latest_release[:buildVersion].to_i + 1
    end

    puts "Build number: #{build_number}"

    sh("flutter build apk --release --dart-define-from-file=.env --build-number=#{build_number} --no-pub")
   
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      release_notes: release_notes,
      groups: "internal"
    )
  end
end
