name: Deploy android app

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  deploy_android:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ vars.TIMEOUT_MINUTES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: ${{ vars.FLUTTER_VERSION }}
            cache: true

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        run: echo "Upload completed"
