name: Deploy android app

on:
  pull_request: 
    branches:
      - main
    types:
      - closed
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'assets/**'
      - 'android/**'
      - '.github/workflows/deploy_android.yml'
  push:
    branches:
      - main
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'assets/**'
      - 'android/**'
      - '.github/workflows/deploy_android.yml'
      
jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_ANDROID) }}
    environment: production
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/android/Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: ${{ vars.FLUTTER_VERSION }}
            cache: true

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ vars.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup Firebase
        run: |
          npm install -g firebase-tools
          dart pub global activate flutterfire_cli
          flutterfire configure \
            --yes \
            --project="${{ secrets.FIREBASE_PROJECT_ID }}" \
            --platforms="android"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Generate Release Notes
        id: release_notes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TITLE="${{ github.event.pull_request.title }}"
            BODY="${{ github.event.pull_request.body }}"
            RELEASE_NOTES=$(printf "PR: %s\n\n%s" "$TITLE" "$BODY")
          else
            RELEASE_NOTES=$(git log -1 --pretty=%B)
          fi

          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build & Upload APK to Firebase App Distribution
        run: |
          # Signing APK
          cd ${{ github.workspace }}/android/app
          echo "${{ secrets.ANDROID_KEY_STORE }}" > upload-keystore.txt
          base64 -d upload-keystore.txt > upload-keystore.jks
          cd ${{ github.workspace }}/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
          echo "storeFile=upload-keystore.jks" >> key.properties

          # Setup google credentials for firebase app distribution
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}' > service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service_account.json

          # Setup flutter dart define
          cd ${{ github.workspace }}
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "BASE_URL=${{ vars.WEB_SOCKET_URL }}" >> .env

          # Build and upload
          cd ${{ github.workspace }}/android
          bundle exec fastlane build_and_upload_to_firebase_app_distribution
        env:
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          RELEASE_NOTES: ${{ steps.release_notes.outputs.changelog }}
          ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}