name: Deploy ios app

on:
  push: 
    branches:
      - main
      
jobs:
  deploy_ios:
    runs-on: macos-latest
    timeout-minutes: ${{ fromJSON(vars.TIMEOUT_MINUTES_IOS) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: ${{ vars.FLUTTER_VERSION }}
            cache: true
            # pub-cache-path: ~/.pub-cache
            # pub-cache-key: "pub-:os:-:arch:-:channel:-:version:-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}"

      - name: Get Flutter Dependencies
        if: steps.flutter-action.outputs.PUB-CACHE-HIT != 'true'
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ vars.RUBY_VERSION }}

      - name: Build iOS
        run: |
          cd ios
          bundle install
          bundle exec fastlane hello
      
      # - name: Build release IPA
      #   run: flutter build ipa --release

      # - name: Upload to Testflight
      #   run: echo "Upload completed"
